// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcU1mNzWFsgsFZpKWRpjd5gpZqY-Rcug',
    appId: '1:486184726817:web:de604f782bd2c15f7b0e60',
    messagingSenderId: '486184726817',
    projectId: 'care-connect-43528',
    authDomain: 'care-connect-43528.firebaseapp.com',
    storageBucket: 'care-connect-43528.appspot.com',
    measurementId: 'G-8LGG3K0HZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhe_eL9DiR6KsgJqeZ-G0gU0gzDmAy3X8',
    appId: '1:486184726817:android:3f58dcd4b511f03b7b0e60',
    messagingSenderId: '486184726817',
    projectId: 'care-connect-43528',
    storageBucket: 'care-connect-43528.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADCDPumBoshKlWaoLNYDw7uNPCLV2dNKE',
    appId: '1:486184726817:ios:fbf7fdd8750d2b9f7b0e60',
    messagingSenderId: '486184726817',
    projectId: 'care-connect-43528',
    storageBucket: 'care-connect-43528.appspot.com',
    iosBundleId: 'com.example.careConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADCDPumBoshKlWaoLNYDw7uNPCLV2dNKE',
    appId: '1:486184726817:ios:3261d7155322db277b0e60',
    messagingSenderId: '486184726817',
    projectId: 'care-connect-43528',
    storageBucket: 'care-connect-43528.appspot.com',
    iosBundleId: 'com.example.careConnect.RunnerTests',
  );
}
